Clean up clang build. v4 still fails, but pushing anyway.
Signed-off-by: Bryan Bayerdorffer <bryanb@qti.qualcomm.com>

diff --git a/scripts/Makefile.inc.test b/scripts/Makefile.inc.test
--- a/scripts/Makefile.inc.test
+++ b/scripts/Makefile.inc.test
@@ -357,8 +357,10 @@ endif
 	if [ $$? -ne 0 ]; then echo -e "FAIL ${TEST}\nbuild fail"|tee test.log; fi
 
 ${EXEC}: ${OBJS} constants
-	${CC} -o $@ ${OBJS} ${LDFLAGS}; \
-	if [ $$? -ne 0 ]; then echo -e "FAIL ${TEST}\nbuild fail"|tee test.log; fi
+	# How's this for an ugly hack?
+	${CC} -o $@ ${OBJS} ${LDFLAGS} 2>&1 | perl -pe 's/.*Symbol.*__h2_handle_errors_hook__.*is defined in both linker script and input file.*//'; \
+	CODE=$${PIPESTATUS[0]}; \
+	if [ "$$CODE" -ne 0 ]; then echo -e "FAIL ${TEST}\nbuild fail"|tee test.log; fi
 
 ignore_fns: ${OBJS}
 	${H2DIR}/scripts/gen_ignore_fns.pl ${OBJS} > $@
