Profiling re-enabled, worked around limitation on current cov tools
Signed-off-by: Josef Wells <jwells@qti.qualcomm.com>

diff --git a/scripts/Makefile.inc.test b/scripts/Makefile.inc.test
--- a/scripts/Makefile.inc.test
+++ b/scripts/Makefile.inc.test
@@ -281,8 +281,7 @@ ${EXEC}: ${OBJS}
 
 # each test has a max of 60 seconds!
 test.log: ${EXEC}
-#	ulimit -t 60 && ${SIM} ${SIMF} --profile -- ${BOOTER} ${EXEC} | tee $@; 
-	ulimit -t 60 && ${SIM} ${SIMF} -- ${BOOTER} ${EXEC} | tee $@; \
+	ulimit -t 60 && ${SIM} ${SIMF} --profile -- ${BOOTER} ${EXEC} | tee $@; \
 	CODE=$${PIPESTATUS[0]}; \
 	if [ "$$CODE" -eq 137 ]; then \
 	   echo -e "\nERROR: ${TEST}: probably ulimit" >> $@; \
@@ -291,19 +290,14 @@ test.log: ${EXEC}
 # Coverage stuff -- single testcase
 
 gmon.out: test.log
-#	${GMON_MERGE} -o gmon.out gmon.t_*
-	touch gmon.out
+	${GMON_MERGE} -o gmon.out gmon.t_*
 
-COVFILES=cov.txtG
+COVFILES=cov.txt
 GMON_FILES=gmon.out gmon.t_0 gmon.t_1 gmon.t_2 gmon.t_3 gmon.t_4 gmon.t_5
 
-#${COVFILES}: ${EXEC} gmon
-#	${COV} -i ${EXEC} -o cov.txt -c cov.csv gmon
-
 ${COVFILES}: ${DUMP} gmon.out
-#	${COV} -F -d ${DUMP} -o cov.txt gmon.out; \
-#	if [ $$? -ne 0 ]; then echo -e "FAIL ${TEST}\ncoverage fail"; exit 1; fi
-	touch ${COVFILES}
+	${COV} -F -d ${DUMP} -o cov.txt gmon.out; \
+	if [ $$? -ne 0 ]; then echo -e "FAIL ${TEST}\ncoverage fail"; exit 1; fi
 
 CLEANUP=${PYTHON_GENERATED_FILES} ${OBJS} ${EXEC} ${COVFILES} ${GMON_FILES} ${DUMP} make.log test.log results.txt h2
 CLEANUP += stats.txt stats_help.txt ihist.txt prof.txt
