Generate proper PASS/FAIL for each test.
Signed-off-by: Bryan Bayerdorffer <bryanb@qti.qualcomm.com>

diff --git a/scripts/Makefile.inc.test b/scripts/Makefile.inc.test
--- a/scripts/Makefile.inc.test
+++ b/scripts/Makefile.inc.test
@@ -129,7 +129,7 @@ clean_libs:
 	rm -rf install; $(MAKE) clean
 
 clean_top:
-	rm -Rf test.cov_fns cov.txt report.html make.log
+	rm -Rf test.cov_fns cov.txt report.html qurt_report.html make.log
 
 
 ################################################################################
@@ -252,6 +252,30 @@ report.html:
 	done;\
 	echo "</table></body></html>" >> report.html;
 
+qurt_report.html:
+	@echo "<html><body><table>" > qurt_report.html;\
+	for SUBDIR in ${SUBDIRS}; do\
+	   echo "<tr><td> $$SUBDIR</td>" >> qurt_report.html;\
+	   if [ ! -s $$SUBDIR/src/results.txt ]; then\
+	      echo '<td><font style="background-color: red;">' >> qurt_report.html; \
+	      echo 'Missing results.txt, that should not be!' >> qurt_report.html; \
+	      echo '</font></td>' >> qurt_report.html; \
+	   else\
+	      grep "TEST PASSED" $$SUBDIR/src/results.txt > /dev/null; \
+	      if [ $$? -eq 0 ]; then \
+	         echo '<td>' >> qurt_report.html; \
+		 cat $$SUBDIR/src/results.txt >> qurt_report.html; \
+		 echo '</td>' >> qurt_report.html; \
+	      else \
+	         echo '<td><font style="background-color: red;">' >> qurt_report.html; \
+		 cat $$SUBDIR/src/results.txt >> qurt_report.html; \
+		 echo '</font></td>' >> qurt_report.html; \
+	      fi; \
+	   fi; \
+	   cat $$SUBDIR/src/make.log >> make.log;\
+	done;\
+	echo "</table></body></html>" >> qurt_report.html;
+
 .PHONY: check
 
 check-fail:
@@ -364,8 +388,16 @@ test.log: ${EXEC}
 	echo PKW_hexagon-tools $(PKW_hexagon-tools) >> $@
 	ulimit -t ${ULIMIT} && ${RUN} ${SIMF} --profile -- ${BOOTER} ${BOOTER_ARGS} ${EXEC} | tee -a $@; \
 	CODE=$${PIPESTATUS[0]}; \
+	echo exit status == $$CODE; \
 	if [ "$$CODE" -eq 137 ]; then \
 	   echo -e "\nERROR: ${TEST}: probably ulimit" >> $@; \
+	fi; \
+	if [ "$$QURT_TEST" != "" ]; then \
+		if [ "$$CODE" -ne 0 ]; then \
+			echo "FAIL" >> $@; \
+		else \
+			echo "TEST PASSED" >> $@; \
+		fi; \
 	fi;
 	$(POST_RUN)
 
