Fix consts calculations for tests.
Signed-off-by: Bryan Bayerdorffer <bryanb@qti.qualcomm.com>

diff --git a/scripts/Makefile.inc.test b/scripts/Makefile.inc.test
--- a/scripts/Makefile.inc.test
+++ b/scripts/Makefile.inc.test
@@ -17,6 +17,10 @@ MAKE_INC_TEST := 1
 
 default-target: all
 
+# overrides for tests linked in kernel space
+H2K_HEAP_SIZE =  0x00010000
+H2K_STACK_SIZE = 0x00001000
+
 include $(H2DIR)/scripts/Makefile.inc.config
 include $(H2DIR)/scripts/Makefile.inc.opensource
 include $(H2DIR)/scripts/Makefile.inc.version
@@ -37,10 +41,6 @@ else
       MODELSTR = ${MODEL}_v${ARCHV}
    endif
 endif
-
-# overrides for tests linked in kernel space
-H2K_HEAP_SIZE =  0x00010000
-H2K_STACK_SIZE = 0x00001000
 
 ifeq ($(INSTALLPATH),)
 export INSTALLPATH := $(H2DIR)/install
@@ -140,6 +140,8 @@ OPTIMIZE := -O1
 # monitor space
 
 KERNEL_INCLUDES := -I ${H2DIR}/kernel/include -I ${H2DIR}/libs/h2/common
+
+H2K_KERNEL_NPAGES ?= 0
 
 LDFLAGS += -Wl,--defsym=__bootvm_entry_point=hexagon_pre_main -Wl,--defsym=__bootvm_entry=qdsp6_pre_main -Wl,--defsym=H2K_KERNEL_NPAGES=$(H2K_KERNEL_NPAGES) -Wl,--defsym=H2K_LOAD_ADDR=$(H2K_LINK_ADDR) -Wl,-e=start # -Wl,--defsym=__entry=$(H2K_LOAD_ADDR)
 
@@ -360,7 +362,13 @@ endif
 	${CC} ${ASFLAGS} -c -o $@ $<; \
 	if [ $$? -ne 0 ]; then echo -e "FAIL ${TEST}\nbuild fail"|tee test.log; fi
 
-${EXEC}: ${OBJS} | constants
+${EXEC}_tmp: ${OBJS}
+# How's this for an ugly hack?
+	${CC} -o $@ ${OBJS} ${LDFLAGS} 2>&1 | perl -pe 's/.*Symbol.*__h2_.*_hook__.*is defined in both linker script and input file.*//'; \
+	CODE=$${PIPESTATUS[0]}; \
+	if [ "$$CODE" -ne 0 ]; then echo -e "FAIL ${TEST}\nbuild fail"|tee test.log; fi
+
+${EXEC}: ${EXEC}_tmp | constants
 # How's this for an ugly hack?
 	${CC} -o $@ ${OBJS} ${LDFLAGS} 2>&1 | perl -pe 's/.*Symbol.*__h2_.*_hook__.*is defined in both linker script and input file.*//'; \
 	CODE=$${PIPESTATUS[0]}; \
